kubejs/client_scripts/deprecation.js, kubejs/client_scripts/example.js, kubejs/server_scripts/deprecation.js
Script hides old mods/items and removes their default recipes.
Also adds conversion recipes to from old items/mods to new items/mods
=> Add script for deprecating items/mods

kubejs/client_scripts/tooltips.js, kubejs/server_scripts/EMIThings/info.js
Adds tooltips to:
- Pipez: Pipes show much much they transfer with what upgrades, and upgrades show how much they transfer of what type.
- Took Pipe Connector info page from EMI and put it into a tooltip.
- Added tooltips for JustDireThings raw ores to explain how to get them, also info page for Unstable Portal Fluid
- Tooltip for AE2WTLib quantum bridge card on how to use it.
=> Helpful tooltips, and info for a few mods.

config/ftbquests/quests/chapters/Theurgy.snbt
Like Powah! earlier, this re-proportions Theurgy to fit to the screen when centered and zoom re-set in ftbq, @ UI=3, 1080p.
=> center and proportion/fit Theurgy

config/ftbquests/quests/chapters/Applied Energistics.snbt
a small commit; dunno how I missed this last night.
=> removed stray extra AE2 title image

config/ftbquests/quests/chapters/Welcome.snbt
=> make Getting Started center on 0 key

config/ftbquests/quests/lang/en_us.snbt
- ignored/didn't check made-up words from mods
- spell checker trips on chat-formatted words; may be misses do to manually skipping those
=> One spelling pass, on current main.

config/ftbquests/quests/chapters/Theurgy.snbt
just restores the four gems in the sky—in the quest for Theurgy—did nat
=> used new names for gem textures

config/ftbquests/quests/chapters/Storage.snbt
Deleted and re-created all backpack tasks, and set MDC to strict.
This should address issue #72.
=> fixed backpack tier quests

config/ftbquests/quests/chapters/Mekanism Ore Processing.snbt, config/ftbquests/quests/lang/en_us.snbt
Sticking with the diagram/flowchart theme... no descriptions! (waaa???)
Added an initial start quest explaining this chapter is layed out like a flow chart, there are start points for each tier, and the production ratio for each tier (though the latter is already in each tier's start quest title.)
=> added explanatory starting quest

kubejs/server_scripts/Mods/Craftoria/Compression.js
Shows how many blocks they contain, holding shift shows precise number
=> Tooltips for compressed blocks

config/ftbquests/quests/chapters/Mobs & Chaos.snbt
fixes mob face textures on _Mobs & Chaos_ chapter.
=> fix mob faces

config/ftbquests/quests/chapters/Mekanism.snbt, config/ftbquests/quests/lang/en_us.snbt
=> All Mekanism Quest Descriptions

config/ftbquests/quests/chapters/Mekanism.snbt, config/ftbquests/quests/lang/en_us.snbt
matrix, heater and adv solar, make freerunner and stuff optional, move matrix, QIO not required, teleporter stuff not required
=> fix some mek stuff

config/ftbquests/quests/chapters/Mekanism Ore Processing.snbt, config/ftbquests/quests/lang/en_us.snbt
=> Some fixes for Mek Ore Proc. chapter

config/ftbquests/quests/chapters/Relics and Artifacts.snbt
=> Re-style of Artifacts & Relics

config/ftbquests/quests/chapters/Agriculture.snbt
Renaming "Feeding Trough Quest" to "Feeding & Gathering", made quest inclusive of Animal Feeding Troughs mod
=> Agriculture Quest Work

config/ftbquests/quests/chapters/Theurgy.snbt, config/ftbquests/quests/chapters/irons_spells.snbt, config/ftbquests/quests/lang/en_us.snbt
50% of quest descriptions done
=> adding Irons spells, and reworked Theurgy

kubejs/data/powah/data_maps/fluid/fluid_coolant.json
=> added more powah coolants

kubejs/server_scripts/unify/mekProcessing.js
Add sawmill helper function, add plank recipes so the output of modded logs have parity with vanilla log types
=> The Plankening

config/ftbquests/quests/chapters/Modern Industrialization.snbt, config/ftbquests/quests/lang/en_us.snbt
better descriptions for spawner upgrades and quests for basic upgrade (due to it's new cheaper recipe (default MI change)), and the redstone module and overdrive module.
=> spawner upgrades and MI quests

config/ftbquests/quests/chapters/Ars Nouveau.snbt, config/ftbquests/quests/lang/en_us.snbt
```
+ Quests (the crab Alaka something, Villager, Ars Ocultas mention, Ars Delight mention)
+ Some graphics for quest chapter (check image below)
+ Quest rewards (codex glyph level 2 & 3, useful items) to some quests
* Quests (adding/adjusting description to many quests, the image should have some)
+: adding
*: changing
```
=> Ars quest final. Only typos fix from now

config/ftbquests/quests/chapters/Theurgy.snbt, config/ftbquests/quests/lang/en_us.snbt
I've long since felt the Theurgy quests were kind of lacking. To that, I both rewrote a bunch of existing text, and added new text, to every quest in the questline. The result is a marked improvement, I feel.
=> Rewrite Theurgy quests

config/ftbquests/quests/chapters/Occultism.snbt, config/ftbquests/quests/lang/en_us.snbt
This reworks the Occultism quest line to more accurately reflect its updated progression. It also changes all familiar summoning tasks to actually require summoning them, not killing them.
This will likely take some work to merge, as I worked on a 1.14.0 instance, forgetting that by now there's surely been at least a few lang changes to the quests....
=> Occultism quest rewrite

config/ftbquests/quests/chapters/Occultism.snbt, config/ftbquests/quests/lang/en_us.snbt
=> If it a first you don't succeed... [Conflict resolution on merge of PR414]

kubejs/server_scripts/EMIThings/info.js, kubejs/server_scripts/Mods/Craftoria/InfinityCells.js
Added shapeless craft + info for filled trinity gem since the Occultism ritual doesn't seem to function with partial NBT
=> Update Infinity Warden Souls Cell recipe

kubejs/server_scripts/Mods/HostileNeuralNetworks/DataModels.js
This pull request refactors the model data generation into a helper function with improved type safety.
=> refactor: extract model data generation into helper with type safety

kubejs/server_scripts/unify/storage_upgrades.js
Fix Sophisticated Storage Upgrade unification not loading on first world join
=> Fix Sophisticated Storage Upgrade unification

kubejs/server_scripts/Mods/SophisticatedStorage/Recipes.js
fix sophisticated storage input, output and IO accepting only one type of chest/barrel
=> fix soph storage input output and io recipe

kubejs/assets/ftbquests/ftb_quests_theme.txt
- FTBQ theme file how has "unavailble" dep. line color option
- So made use of it
- Some further dep. line color tweaking for a few chapters
- Resorted sections (chapters) to keep in order by ID number
- Also added comments with real chapter names
=> Touchup for FTB Theme

config/ftbquests/quests/chapter_groups.snbt, config/ftbquests/quests/chapters/Gardening.snbt, config/ftbquests/quests/chapters/cooking.snbt, config/ftbquests/quests/lang/en_us.snbt
- added Agriculture chapter group - updated its font to match the other chapter groups - ordered it among the chapter groups in a way that i thought made sense - gave it a symbol (clover leaf) - SYMBOL STILL NEEDS A COLOR
- added Gardening chapter - filled with quests and dependencies (no rewards set up yet, don't know what to do for that) - updated capitalization both in the title and contents of file
- added cooking chapter (empty)
- checked lang file to make sure no fuckery was happening
=> Added Gardening Quest Chapter

automation/changelog-gen-docs.md, automation/craftoria_changelog.py
- refactor: move commit filters to config
- feat: use OS-independent search to find Git
- feat: automatically remove reverted commits
- fix: mod changes not showing as bullet points
- refactor: general readability improvements
- feat: add alphabetical sorting
- feat: add cutoff commit hash as config option
=> Refactor changelog generator until replaced

config/perception.yaml
This pull request disables Perception's shake module.
=> feat: disable perception shake module

README.md
added discord server link to readme
=> added discord server link to readme

kubejs/data/moderndynamics/attachment_upgrades/mekanism/elite_control_circuit.json, kubejs/data/moderndynamics/attachment_upgrades/mekanism/ultimate_control_circuit.json, kubejs/data/moderndynamics/attachment_upgrades/modern_industrialization/advanced_motor.json, kubejs/data/moderndynamics/attachment_upgrades/modern_industrialization/advanced_pump.json, kubejs/data/moderndynamics/attachment_upgrades/modern_industrialization/large_advanced_motor.json, kubejs/data/moderndynamics/attachment_upgrades/modern_industrialization/large_advanced_pump.json, kubejs/data/moderndynamics/attachment_upgrades/modern_industrialization/large_motor.json, kubejs/data/moderndynamics/attachment_upgrades/modern_industrialization/large_pump.json
added more later game stuff to make MD pipes more useful for high flow application (better than pipez)
=> who needs pipez when MD is peak

kubejs/server_scripts/tags.js
pulled tag changes from mod since it hasnt received an update to fix it https://github.com/KyaniteMods/DeeperAndDarker/commit/84c2cc4cfdf90f54bd75f1f18fd07a2070dee3d1
=> fix deeper and darker enchants from #626
