- kubejs/server_scripts/unify/reloadOnLoad.js
I have absolutely 0 idea why this is required, but for some reason KubeJS scripts error out on first world load, and they work just fine after doing a "/reload" after loading in, so this file just does that command on world load.
I will probably go through the script later on to implement a proper fix, but this works for now.
> "Fixes" unify script not working completely on world load.

- config/ftbquests/quests/chapters/Mekanism Ore Processing.snbt
My bad. I do like to break peeps out of linear thinking, but after discussing it with a player (only hours after the update hit! ^^) I think it best for their tiers to be completable independently, even though each higher one subsumes the previous.
> allow lower tier quests to complete before higher ones

- server_files/server-setup-config.yaml
Draft until I test on Windows too.
> Un-needed lines in server-setup-config.yaml result in server running with JFR enabled

- config/ftbquests/quests/chapters/Mekanism Ore Processing.snbt
Makes them check mark tasks instead, while retaining their proper/informative quest icon.
The dirty and clean iron slurries are left alone... will attend to those with a working EMI instance later. Nothing depends on them though.
> Fix M.O.P. substance-in-a-chemical-tank tasks

- config/ftbquests/quests/lang/en_us.snbt
Compressed blocks are blacklisted from duplication through the MI Replicator, but that is not mentioned in the quest. This can cause some players to think they can replicate hundreds of millions of resources using a single bucket of UU Matter, when in fact trying to do so "will be a fruitless endeavor."
> Mention compressed blocks blacklist in MI Replicator quest

- config/ftbquests/quests/chapters/PneumaticCraft.snbt
- config/ftbquests/quests/lang/en_us.snbt
This PR swaps Logistics Drone & Logistic Frame quest nodes & adds missing quest information for Logistic Frames.
Quest text could use input from someone with a better feel for consistency & formatting used throughout the rest of Craftoria quests.
> PNC quest updates

- config/Mekanism/tools-materials-startup.toml
The default value of `refined_obsidianHoeDamage` in Mekanism Tools' `tools-materials-startup.toml` config file is incompatible with the value of `refined_obsidianAttackDamage` in such a way that the automatic fixer which runs when invalid config values are detected tries to run repeatedly to no effect while filling up the log files.
I've changed the `refined_obsidianHoeDamage` value to `-5.0`, which is the lowest supported value given the value of `refined_obsidianAttackDamage`. This should fix the repeating error.
(The default value of `refined_obsidianAttackDamage` is `8.0`, but the current value was reduced to `5.0` during modpack balancing, causing the error.)
> Fix incorrect value in Mekanism tools config

- config/ftbquests/quests/lang/en_us.snbt
According to the source code of Modern Industrialization, which the Plasma Turbine is from, the turbine's exact EU generation rate is 1,048,576 EU/t, not 1,049,000 EU/t. The 1,049,000 EU/t value comes from the tooltip which shows the generation rate rounded to the thousands place as 1.049M EU/t.
The relevant code can be found here (note `1 << 20 == 1048576`):
https://github.com/AztechMC/Modern-Industrialization/blob/5d9c1b69f3d6d683554f2003f6c688b89909e676/src/main/java/aztech/modern_industrialization/machines/init/MultiblockMachines.java#L542-L547
> Be more precise for Plasma Turbine EU generation rate

- kubejs/server_scripts/Mods/ModernIndustrialization/Quarry.js
This brings the netherrack output when using MI Gold Drills in line with base MI, allowing setups which void netherrack from gold drills by not putting in any hatches for it to work properly in Craftoria.
See also https://github.com/AztechMC/Modern-Industrialization/commit/c09303598d27e96a785ff7f29da1721ad14b09c8, which contains the latest (as of 2.2.30) cobblestone and netherrack output amounts and probabilities in base MI.
> Lower netherrack output through MI gold drill again by making it probabilistic

- kubejs/server_scripts/tags.js
`minecraft:wardern` does not exist; but the intent there was to disable the creation of Warden spawn eggs through Mob Grinding Utils. The entry is fixed to the correct value of `minecraft:warden`.
The incorrect entry was added in b79e6f37c8ba84aa95d1279d455953aa5f620b8d.
> Fix incorrect tag entry (`wardern` → `warden`)

- kubejs/server_scripts/Mods/BiomesWeveGone/Recipes.js
- kubejs/server_scripts/Mods/BiomesWeveGone/Tags.js
Hope this pull request is alright... I've noticed you cannot crush any items from other mods in crusher than vanilla to make bio fuel, so I've added a few recipes from Oh The Biome's We've Gone items which are basically everywhere so you can use them too.
Since this is my first work with KubeJS, I'll take any suggestions or ideas if there's anything to improve or change.
Thanks!
> Add bio fuel recipes for Mekanism from Biomes We've Gone plants and other items

- config/Mekanism/gear.toml
- config/mekanismcovers.json
- kubejs/server_scripts/Mods/Mekanism/Recipes.js
- kubejs/server_scripts/tags.js
The Mekanism jetpack was excessively overpowered in the early game and underwhelming in the mid to late game. To address these issues, I have integrated compatibility with the Curios API and refined its recipe for improved balance.
> Add Curios support for Mekanism Jetpack; adjust recipe balance.

- kubejs/server_scripts/Mods/Replication/Recipes.js
This pull request allows Matter Tanks matter values to be reset on craft, eliminating the need to delete unwanted tanks
> fix: allow for matter tanks uncrafting

- kubejs/server_scripts/removals.js
This pull request disables the Anti-Personnel and Confiscation modules from Modular Force Field Systems. Currently, the Anti-Personnel module has an unexpected behavior where, when a player is killed, their inventory loot is dropped into the world, while items in the curios slots remain in the grave. This can lead to players intentionally stealing loot from others and other undesirable consequences, effectively breaking the functionality of graves.
The Confiscation module, as the name suggests, allows items to be stolen from players, which isn't ideal for a non-PvP-focused modpack. Personally, I would remove the mod entirely due to various server performance issues and because other mods already provide similar mechanics, such as chunk banning players or preventing mob spawns in certain …
> fix: disable Anti-Personnel and Confiscation modules in MFFS

- kubejs/server_scripts/Mods/Mekanism/Recipes.js
This pull request replaces mekanism diamond dust tag in the armored jetpack recipe. Fixing the recipe not working.
> fix: update armored jetpack recipe to use diamond dusts tag

- kubejs/server_scripts/tags.js
This pull request introduces the `craftoria:mob_blacklist` tag and integrates it with Industrial Foregoing's Mob Duplicator blacklist.
> Add mob blacklist tag and integrate with Mob Duplicator blacklist

- kubejs/server_scripts/Mods/Craftoria/ConflictFixes.js
- kubejs/server_scripts/tags.js
- kubejs/startup_scripts/Globals.js
This pull request simplifies dye color handling by using the `Color` namespace.
> refactor: replace global `dyeColors` with `Color.DYE`

- kubejs/data/industrialforegoing/recipe/laser_drill_ore/ancient_debris.json
This pull request adds the JAMD Nether dimension to the whitelist for the IF laser drilling ancient debris recipe.
> feat: whitelist JAMD Nether for IF laser drilling ancient debris recipe

- kubejs/data/actuallyadditions/advancement/pickup_coffee.json
- kubejs/server_scripts/tags.js
This pull request unifies the tags for coffee beans between Actually Additions and Rustic Delight, resolving the issue with the coffee maker recipe. Also updates the advancement for picking up coffee beans to reference the Rustic Delight tag instead of the Actually Additions tag.
> Unify coffee beans between Actually Additions and Rustic Delight

- kubejs/server_scripts/Mods/SophisticatedStorage/Recipes.js
- kubejs/server_scripts/tags.js
This pull request fixes an issue where the Sophisticated Storage controller recipe only accepted one specific type of wooden chest or barrel from Sophisticated Storage. Now, the recipe works with all the different types available. This fix addresses issue #495 .
> fix sophisticated storage controller recipe accepting only one type of chest/barrel

- kubejs/startup_scripts/Globals.js
This pull request updates the Craftoria mod name(currently the modid) from `craftoria` to `Craftoria` using the Platform namespace.
> feat: explicitly set craftoria mod name to "Craftoria"

- .editorconfig
- .gitattributes
- .prettierrc.json
This pull requests adds standard configuration files to maintain consistent code formatting and editor settings:
- `.prettierrc.json` for code formatting rules
- `.gitattributes` for consistent line endings handling
- `.editorconfig` for basic editor preferences
> Add base editor configuration files

- kubejs/server_scripts/Mods/FarmingForBlockheads/market.js
This pull request removes Actually Additions coffee beans from the FFB market, as they've been unified with Rustic Delight's and now have no usage or recipes.
> fix: remove Actually Additions coffee beans from FFB market

- kubejs/server_scripts/Mods/Mekanism/Edibles.js
- kubejs/startup_scripts/Custom/Items.js
Allow players to eat polonium/plutonium pellets as well as yellow cake
> Make mekanism pellets and yellow cake edible

- kubejs/server_scripts/EMIThings/Hide.js
- kubejs/server_scripts/EMIThings/info.js
- kubejs/server_scripts/Mods/AE2/MegaCells.js
- kubejs/server_scripts/Mods/Apothic/Spawners.js
- kubejs/server_scripts/Mods/HostileNeuralNetworks/DataModels.js
- kubejs/server_scripts/Mods/ModernIndustrialization/Info.js
- kubejs/server_scripts/Mods/ModernIndustrialization/QoL.js
- kubejs/server_scripts/Mods/ModernIndustrialization/Quarry.js
- kubejs/server_scripts/Mods/ModernIndustrialization/Recipes.js
- kubejs/server_scripts/Mods/ModernIndustrialization/ReplicatorBlacklist.js
- kubejs/server_scripts/Mods/Powah/Recipes.js
- kubejs/server_scripts/helpers/ae2.js
- kubejs/server_scripts/helpers/ars_nouveau.js
- kubejs/server_scripts/helpers/create.js
- kubejs/server_scripts/helpers/industrial_foregoing.js
- kubejs/server_scripts/helpers/mekanism.js
- kubejs/server_scripts/helpers/modern_industrialization.js
- kubejs/server_scripts/removals.js
- kubejs/server_scripts/unify/Knife.js
- kubejs/server_scripts/unify/general.js
- kubejs/startup_scripts/Custom/InfinityCells.js
Used `$ItemStack_` where quantities can be defined, instead of `Special.Item`(primarely for clarity). Used `Special.*` when possible, as it is a global namespace.
Minor refactors to enable adding JSDoc.
Replaced invalid `for (let [k, v] in obj)` loops with `for (let [k, v] of Object.entries(obj))`. This works in KubeJS but isn't valid JavaScript syntax.
> refactor(docs): update and add JSDoc types

- kubejs/server_scripts/unify/storage_upgrades.js
add a storageUnique as a blacklist filter and exclude hopper upgrades. This fix addresses issue #513
> exclude hopper upgrades when unifying storage upgrades

- kubejs/server_scripts/Mods/ModernIndustrialization/Recipes.js
Add a way to convert uraninite (UO2) to 100mB of oxygen and 1 raw uranium and opposite with MI chemical reactor
> QoL: Add uraninite conversion to uranium with chemical reactor

- kubejs/server_scripts/Mods/MobGrindingUtils/HopperFix.js
This pull request prevents using hoppers to upgrade mob mashers, bypassing limits.
Temporary workaround for https://github.com/vadis365/Mob-Grinding-Utils/issues/328, pending a fix from the MGU author (no commits since Dec 2024)
> fix: prevent vanilla hopper placement near mob mashers

- kubejs/server_scripts/Mods/Apothic/Gateways.js
This pull request fixes an error where `boss` was treated as an object (boss.id) instead of a string. Resulting in custom bosses not being loaded.
> fix: resolve undefined invader path for custom bosses

- kubejs/client_scripts/Keybinds.js
Removing some mods (like toomanyrecipeviewers) creates a situation where the jade keybindings no longer exist. 
This pull request adds handling to look up the keybinding and if it doesnt exist, it skips that key modification. This should handle cases where keybindings are added to namespaces that dont match their mod id.
This also wraps the modification in a try-catch in case modification fails so that failed keybinding modification doesnt prevent client load.
> Add missing keybinding and generic error handling to keybindjs script

- automation/scripts/README.md
- automation/scripts/package.json
- automation/scripts/src/generate-changelog.js
- automation/scripts/src/utils.js
- Fix "Nothing Changed" display in both main and mod changelogs (corrected typo + addition)
- Allow script to be run from any directory by setting cwd before config initialization(corrected typo*)
Both of these were intended to be already in, but I realized I made some silly mistakes in line positions and a few other things😔
> Improve changelog display and script portability

- config/jamd/mining.json
Adds:
```
- crimsite
- asurine
- ochrum
```
I just copied the existing section for mi:antimony, and used that for each of these, but also cut the "count" in half.
PR'ing this in case you gents have opinions.
Cheers.
> Add Create decorative stones in jamd

- kubejs/server_scripts/Mods/ModernIndustrialization/DataMaps.js
PneumaticCraft fluid fuels can be burned directly in MI's boilers and diesel generators.
The fuel values are based off the corresponding fuels from MI where said fuel exists there, and are otherwise proportional to the burn time of a bucket of the fuel in a furnace.
Fixes https://github.com/TeamAOF/Craftoria/issues/630.
> Make PneumaticCraft fluid fuels directly usable as MI fuels
